//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wch
{
    using System;
    using System.Collections.Generic;
    
    public partial class sv_wch_TimeTable
    {
        public string CourseName { get; set; }
        public int Credit { get; set; }
        public int Period { get; set; }
        public int TimeID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string TeaID { get; set; }
        public Nullable<int> StuNum { get; set; }
        public int Capacity { get; set; }
        public Nullable<bool> AllowView { get; set; }
        public Nullable<byte> Day { get; set; }
        public int TermID { get; set; }
        public string TermName { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> StartChoice { get; set; }
        public Nullable<System.DateTime> EndChoice { get; set; }
        public string DepName { get; set; }
        public string TeaName { get; set; }
        public int TheatreID { get; set; }
        public int SeatCapacity { get; set; }
        public string Site { get; set; }
        public int ScheduleID { get; set; }
        public string TimeSpan { get; set; }
    }
}
