//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wch
{
    using System;
    using System.Collections.Generic;
    
    public partial class sv_wch_courseSelect
    {
        public string StuID { get; set; }
        public string StuName { get; set; }
        public int TimeID { get; set; }
        public string TermName { get; set; }
        public string CourseName { get; set; }
        public string TeaName { get; set; }
        public int Period { get; set; }
        public int Credit { get; set; }
        public string DepName { get; set; }
        public Nullable<double> Mark { get; set; }
    }
}
