//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wch
{
    using System;
    using System.Collections.Generic;
    
    public partial class sv_wch_Student
    {
        public string StuName { get; set; }
        public bool Gender { get; set; }
        public Nullable<byte> StuAge { get; set; }
        public string Tel { get; set; }
        public Nullable<System.DateTime> Grade { get; set; }
        public string Address { get; set; }
        public string ClassName { get; set; }
        public string DepName { get; set; }
        public string StuID { get; set; }
    }
}
