//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wch
{
    using System;
    using System.Collections.Generic;
    
    public partial class sv_wch_StudentSelect
    {
        public int TimeID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string CourseName { get; set; }
        public int Period { get; set; }
        public int Credit { get; set; }
        public Nullable<int> StuNum { get; set; }
        public int Capacity { get; set; }
        public Nullable<bool> AllowView { get; set; }
        public string TeaID { get; set; }
        public string TeaName { get; set; }
    }
}
