//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wch
{
    using System;
    using System.Collections.Generic;
    
    public partial class wch_TimeTable
    {
        public wch_TimeTable()
        {
            this.wch_TimeTableDetail = new HashSet<wch_TimeTableDetail>();
            this.wch_CourseSelection = new HashSet<wch_CourseSelection>();
        }
    
        public int TimeID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string TeaID { get; set; }
        public Nullable<int> StuNum { get; set; }
        public int Capacity { get; set; }
        public Nullable<bool> AllowView { get; set; }
    
        public virtual wch_Course wch_Course { get; set; }
        public virtual wch_Teacher wch_Teacher { get; set; }
        public virtual ICollection<wch_TimeTableDetail> wch_TimeTableDetail { get; set; }
        public virtual ICollection<wch_CourseSelection> wch_CourseSelection { get; set; }
    }
}
