//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wch
{
    using System;
    using System.Collections.Generic;
    
    public partial class wch_CourseSelection
    {
        public string StuID { get; set; }
        public Nullable<int> TimeID { get; set; }
        public Nullable<double> Mark { get; set; }
    
        public virtual wch_Student wch_Student { get; set; }
        public virtual wch_TimeTable wch_TimeTable { get; set; }
    }
}
