//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wch
{
    using System;
    using System.Collections.Generic;
    
    public partial class wch_Student
    {
        public wch_Student()
        {
            this.wch_CourseSelection = new HashSet<wch_CourseSelection>();
        }
    
        public string StuID { get; set; }
        public string StuName { get; set; }
        public bool Gender { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<byte> DepID { get; set; }
        public Nullable<byte> StuAge { get; set; }
        public string Tel { get; set; }
        public Nullable<System.DateTime> Grade { get; set; }
        public string Address { get; set; }
    
        public virtual wch_Class wch_Class { get; set; }
        public virtual ICollection<wch_CourseSelection> wch_CourseSelection { get; set; }
        public virtual wch_Department wch_Department { get; set; }
    }
}
