//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wch
{
    using System;
    using System.Collections.Generic;
    
    public partial class wch_Department
    {
        public wch_Department()
        {
            this.wch_Class = new HashSet<wch_Class>();
            this.wch_Course = new HashSet<wch_Course>();
            this.wch_Student = new HashSet<wch_Student>();
            this.wch_Teacher = new HashSet<wch_Teacher>();
        }
    
        public byte DepID { get; set; }
        public string DepName { get; set; }
    
        public virtual ICollection<wch_Class> wch_Class { get; set; }
        public virtual ICollection<wch_Course> wch_Course { get; set; }
        public virtual ICollection<wch_Student> wch_Student { get; set; }
        public virtual ICollection<wch_Teacher> wch_Teacher { get; set; }
    }
}
